// SPDX-License-Identifier: MIT
#pragma kernel CSPreProcessViewData
#pragma kernel CSIdentifyTileRanges
#pragma kernel CSInitImageRanges
#pragma kernel CSInitNumArgs
#pragma kernel CSInitSortArgs
#pragma kernel CSRenderViewData

#pragma kernel InitDeviceRadixSort
#pragma kernel Upsweep
#pragma kernel Scan
#pragma kernel Downsweep

// #pragma multi_compile __ KEY_UINT KEY_INT KEY_FLOAT KEY_ULONG
// #pragma multi_compile __ PAYLOAD_UINT PAYLOAD_INT PAYLOAD_FLOAT
#pragma multi_compile __ SHOULD_ASCEND
// #pragma multi_compile __ SORT_PAIRS
#pragma multi_compile __ SINGLE_PASS
// #define SINGLE_PASS

// GPU sorting needs wave ops
#pragma require int64
#pragma require wavebasic
#pragma require waveballot
#pragma use_dxc
#pragma enable_d3d11_debug_symbols

cbuffer cbCommon : register(b0)
{
    // Sorting
    uint e_radixShift;
    uint e_min;
    uint e_max;
    uint e_argsOffset;
};

#include "NewDeviceRadixSort.hlsl"
#include "NewGaussianSplatting.hlsl"
#include "UnityCG.cginc"

float4x4 _MatrixObjectToWorld;
float4x4 _MatrixWorldToObject;
float4x4 _MatrixMV;
float4x4 _MatrixPreLeftVP;
float4x4 _MatrixPreRightVP;
float4 _VecScreenParams;
float4 _VecWorldSpaceCameraPos;
int _SelectionMode;

#if defined(SINGLE_PASS)
float4x4 _MatrixLV;
float4x4 _MatrixRV;
float4x4 _MatrixLP;
float4x4 _MatrixRP;
#endif

RWStructuredBuffer<uint> _LeftNumArgs;
RWStructuredBuffer<uint> _RightNumArgs;
RWStructuredBuffer<GeomData> _GeomLeftData;
RWStructuredBuffer<GeomData> _GeomRightData;
RWStructuredBuffer<uint64_t> _BinLeftPointListKey;
RWStructuredBuffer<uint> _BinLeftPointListValue;
RWStructuredBuffer<uint64_t> _BinRightPointListKey;
RWStructuredBuffer<uint> _BinRightPointListValue;
RWStructuredBuffer<uint2> _ImageLeftRange;
RWStructuredBuffer<uint2> _ImageRightRange;
RWStructuredBuffer<uint2> _ImageRange;

StructuredBuffer<uint> _RO_NumArgs;
StructuredBuffer<GeomData> _RO_GeomLeftData;
StructuredBuffer<GeomData> _RO_GeomRightData;
StructuredBuffer<uint64_t> _RO_BinPointListKey;
StructuredBuffer<uint2> _RO_ImageLeftRange;
StructuredBuffer<uint2> _RO_ImageRightRange;
StructuredBuffer<uint> _RO_BinLeftPointListValue;
StructuredBuffer<uint> _RO_BinRightPointListValue;

float4 _TileConfig;
uint _TileScale;

RWStructuredBuffer<uint> _SplatSortDistances;
RWStructuredBuffer<uint> _SplatSortKeys;
uint _SplatCount;

// radix sort etc. friendly, see http://stereopsis.com/radix.html
uint FloatToSortableUint(float f)
{
    uint fu = asuint(f);
    uint mask = -((int)(fu >> 31)) | 0x80000000;
    return fu ^ mask;
}

float _SplatScale;
float _SplatOpacityScale;
uint _SHOrder;
uint _SHOnly;

uint _SplatCutoutsCount;

#define SPLAT_CUTOUT_TYPE_ELLIPSOID 0
#define SPLAT_CUTOUT_TYPE_BOX 1

struct GaussianCutoutShaderData // match GaussianCutout.ShaderData in C#
{
    float4x4 mat;
    uint typeAndFlags;
};
StructuredBuffer<GaussianCutoutShaderData> _SplatCutouts;

RWByteAddressBuffer _SplatSelectedBits;
ByteAddressBuffer _SplatDeletedBits;
uint _SplatBitsValid;

void DecomposeCovariance(float3 cov2d, out float2 v1, out float2 v2)
{
    #if 0 // does not quite give the correct results?

    // https://jsfiddle.net/mattrossman/ehxmtgw6/
    // References:
    // - https://www.youtube.com/watch?v=e50Bj7jn9IQ
    // - https://en.wikipedia.org/wiki/Eigenvalue_algorithm#2%C3%972_matrices
    // - https://people.math.harvard.edu/~knill/teaching/math21b2004/exhibits/2dmatrices/index.html
    float a = cov2d.x;
    float b = cov2d.y;
    float d = cov2d.z;
    float det = a * d - b * b; // matrix is symmetric, so "c" is same as "b"
    float trace = a + d;

    float mean = 0.5 * trace;
    float dist = sqrt(mean * mean - det);

    float lambda1 = mean + dist; // 1st eigenvalue
    float lambda2 = mean - dist; // 2nd eigenvalue

    if (b == 0) {
        // https://twitter.com/the_ross_man/status/1706342719776551360
        if (a > d) v1 = float2(1, 0);
        else v1 = float2(0, 1);
    } else
        v1 = normalize(float2(b, d - lambda2));

    v1.y = -v1.y;
    // The 2nd eigenvector is just a 90 degree rotation of the first since Gaussian axes are orthogonal
    v2 = float2(v1.y, -v1.x);

    // scaling components
    v1 *= sqrt(lambda1);
    v2 *= sqrt(lambda2);

    float radius = 1.5;
    v1 *= radius;
    v2 *= radius;

    #else

    // same as in antimatter15/splat
    float diag1 = cov2d.x, diag2 = cov2d.z, offDiag = cov2d.y;
    float mid = 0.5f * (diag1 + diag2);
    float radius = length(float2((diag1 - diag2) / 2.0, offDiag));
    float lambda1 = mid + radius;
    float lambda2 = max(mid - radius, 0.1);
    float2 diagVec = normalize(float2(offDiag, lambda1 - diag1));
    diagVec.y = -diagVec.y;
    float maxSize = 4096.0;
    v1 = min(sqrt(2.0 * lambda1), maxSize) * diagVec;
    v2 = min(sqrt(2.0 * lambda2), maxSize) * float2(diagVec.y, -diagVec.x);

    #endif
}

bool IsSplatCut(float3 pos)
{
    bool finalCut = false;
    for (uint i = 0; i < _SplatCutoutsCount; ++i)
    {
        GaussianCutoutShaderData cutData = _SplatCutouts[i];
        uint type = cutData.typeAndFlags & 0xFF;
        if (type == 0xFF) // invalid/null cutout, ignore
            continue;
        bool invert = (cutData.typeAndFlags & 0xFF00) != 0;

        float3 cutoutPos = mul(cutData.mat, float4(pos, 1)).xyz;
        if (type == SPLAT_CUTOUT_TYPE_ELLIPSOID)
        {
            if (dot(cutoutPos, cutoutPos) <= 1) return invert;
        }
        if (type == SPLAT_CUTOUT_TYPE_BOX)
        {
            if (all(abs(cutoutPos) <= 1)) return invert;
        }
        finalCut |= !invert;
    }
    return finalCut;
}

#if defined(SINGLE_PASS)
Texture2D<float2> _GSPreDepthTexture;
#else
Texture2D<float> _GSPreDepthTexture;
#endif

[numthreads(GROUP_SIZE, 1, 1)]
void CSPreProcessViewData (uint3 id : SV_DispatchThreadID)
// void CSPreProcessViewData (uint3 id : SV_DispatchThreadID, uint3 group_id : SV_GroupID, uint3 thread_id : SV_GroupThreadID)
{
    uint idx = SwizzleDispatchThreadId(id);
    
    if (idx >= _SplatCount)
        return;
    _GeomLeftData[idx] = (GeomData)0;
    #if defined(SINGLE_PASS)
    _GeomRightData[idx] = (GeomData)0;
    #endif
    
    float4x4 v_left_matrix, p_left_matrix, vp_left_matrix;
    #if defined(SINGLE_PASS)
    v_left_matrix = _MatrixLV;
    p_left_matrix = _MatrixLP;
    vp_left_matrix = mul(p_left_matrix, v_left_matrix);
    
    float4x4 v_right_matrix, p_right_matrix, vp_right_matrix;
    v_right_matrix = _MatrixRV;
    p_right_matrix = _MatrixRP;
    vp_right_matrix = mul(p_right_matrix, v_right_matrix);
    #else
    v_left_matrix = UNITY_MATRIX_V;
    p_left_matrix = UNITY_MATRIX_P;
    vp_left_matrix = UNITY_MATRIX_VP;
    #endif
        
    float3 position = LoadSplatPosValue(idx);
    float3 centerWorldPos = mul(_MatrixObjectToWorld, float4(position,1)).xyz;
    float4 centerLeftClipPos = mul(vp_left_matrix, float4(centerWorldPos, 1));
    
    #if defined(SINGLE_PASS)
    float4 centerRightClipPos = mul(vp_right_matrix, float4(centerWorldPos, 1));
    // 视锥体剔除
    if (!(InFrustum(centerLeftClipPos, _VecScreenParams.zw) || InFrustum(centerRightClipPos, _VecScreenParams.zw))) return;
    #else
    // 视锥体剔除
    if (!InFrustum(centerLeftClipPos, _VecScreenParams.zw)) return;
    #endif
    
    float4 preLeftCenterClipPos = mul(_MatrixPreLeftVP, float4(centerWorldPos, 1));
    float2 preLeftCenterNDCPos = preLeftCenterClipPos.xy / preLeftCenterClipPos.w;
    float2 preLeftMean2d = ((preLeftCenterNDCPos + 1.0f) * _VecScreenParams.xy - 1.0f) * 0.5f;
    preLeftMean2d.x = clamp(preLeftMean2d.x, 0.0f, _VecScreenParams.x);
    preLeftMean2d.y = clamp(preLeftMean2d.y, 0.0f, _VecScreenParams.y);
    
    #if defined(SINGLE_PASS)
    float4 preRightCenterClipPos = mul(_MatrixPreRightVP, float4(centerWorldPos, 1));
    float2 preRightCenterNDCPos = preRightCenterClipPos.xy / preRightCenterClipPos.w;
    float2 preRightMean2d = ((preRightCenterNDCPos + 1.0f) * _VecScreenParams.xy - 1.0f) * 0.5f;
    preRightMean2d.x = clamp(preRightMean2d.x, 0.0f, _VecScreenParams.x);
    preRightMean2d.y = clamp(preRightMean2d.y, 0.0f, _VecScreenParams.y);
    
    float preLeftDepth = _GSPreDepthTexture.Load(int3(preLeftMean2d.x, _VecScreenParams.y - preLeftMean2d.y, 0)).x;
    float preRightDepth = _GSPreDepthTexture.Load(int3(preRightMean2d.x, _VecScreenParams.y - preRightMean2d.y, 0)).y;
    if ((preLeftDepth > 0.001 && centerLeftClipPos.w - preLeftDepth > 0.8) && (preRightDepth > 0.001 && centerRightClipPos.w - preRightDepth > 0.8)) return;
    #else
    // 深度剔除
    float preLeftDepth = _GSPreDepthTexture.Load(int3(preLeftMean2d.x, _VecScreenParams.y - preLeftMean2d.y, 0));
    if (preLeftDepth > 0.001 && centerLeftClipPos.w - preLeftDepth > 0.8) return;
    #endif
    
    half4 color = LoadSplatColor(idx);
    
    // 透明度剔除
    // 1 / 255 = 0.0039;
    if (color.a < 0.004f) return;
    
    bool loadColorFlag = true;
    if (color.r < 0.004f &&
        color.g < 0.004f &&
        color.b < 0.004f)
    {
        loadColorFlag = false;
    }
    
    // 解算 3D 高斯的协方差矩阵
    half opacityScale = _SplatOpacityScale;
    float splatScale = _SplatScale;
    
    float4 boxRot;
    float3 boxSize;
    LoadSplatRotAndScale(idx, boxRot, boxSize);
    float3x3 splatRotScaleMat = CalcMatrixFromRotationScale(boxRot, boxSize);
    float3 cov3d0, cov3d1;
    CalcCovariance3D(splatRotScaleMat, cov3d0, cov3d1);
    float splatScale2 = splatScale * splatScale;
    cov3d0 *= splatScale2;
    cov3d1 *= splatScale2;
    
    // 计算投影中心
    float2 centerLeftNDCPos = centerLeftClipPos.xy / centerLeftClipPos.w;
    // 偏移点云在屏幕坐标系中的位置，整体移动到左下角
    float2 mean_left_2d = ((centerLeftNDCPos - (1.0f - _VecScreenParams.zw) + 1.0f) * _VecScreenParams.xy - 1.0f) * 0.5f;
    
    // 通过 EWA 方法，投影 3D 高斯到平面上的 2D 高斯
    float3 cov_left_2d;
    float3 conic_left_2d;
    float4x4 left_vm = mul(v_left_matrix, _MatrixObjectToWorld);
    cov_left_2d = CalcCovariance2D(position, cov3d0, cov3d1, left_vm, p_left_matrix, _VecScreenParams);
    
    // 计算 SnugBox 的覆盖范围
    float2 bbox_left_argmin, bbox_left_argmax, bbox_left_min, bbox_left_max;
    int2 rect_left_min, rect_left_max;
    if (!DuplicateToTilesTouched(mean_left_2d, cov_left_2d, color.a, _TileConfig,
        conic_left_2d, bbox_left_argmin, bbox_left_argmax, bbox_left_min, bbox_left_max, rect_left_min, rect_left_max)) return;
    
    int y_left_span = rect_left_max.y - rect_left_min.y;
    int x_left_span = rect_left_max.x - rect_left_min.x;
    
    #if defined(SINGLE_PASS)
    // 计算投影中心
    float2 centerRightNDCPos = centerRightClipPos.xy / centerRightClipPos.w;
    // 偏移点云在屏幕坐标系中的位置，整体移动到左下角
    float2 mean_right_2d = ((centerRightNDCPos - (1.0f - _VecScreenParams.zw) + 1.0f) * _VecScreenParams.xy - 1.0f) * 0.5f;
    
    // 通过 EWA 方法，投影 3D 高斯到平面上的 2D 高斯
    float3 cov_right_2d;
    float3 conic_right_2d;
    float4x4 right_vm = mul(v_right_matrix, _MatrixObjectToWorld);
    cov_right_2d = CalcCovariance2D(position, cov3d0, cov3d1, right_vm, p_right_matrix, _VecScreenParams);
    
    // 计算 SnugBox 的覆盖范围
    float2 bbox_right_argmin, bbox_right_argmax, bbox_right_min, bbox_right_max;
    int2 rect_right_min, rect_right_max;
    if (!DuplicateToTilesTouched(mean_right_2d, cov_right_2d, color.a, _TileConfig,
        conic_right_2d, bbox_right_argmin, bbox_right_argmax, bbox_right_min, bbox_right_max, rect_right_min, rect_right_max)) return;
    
    int y_right_span = rect_right_max.y - rect_right_min.y;
    int x_right_span = rect_right_max.x - rect_right_min.x;
    
    if ((y_left_span * x_left_span == 0) && (y_right_span * y_right_span == 0)) return;    
    #else
    // If no tiles are touched, return 0
    if (y_left_span * x_left_span == 0) return;
    #endif
    
    // 求解 SH 球谐函数，得到颜色数据
    float3 worldViewDir;
    worldViewDir = _VecWorldSpaceCameraPos.xyz - centerWorldPos.xyz;
    float4 col;
    if (loadColorFlag)
    {
        float3 objViewDir = mul((float3x3)_MatrixWorldToObject, worldViewDir);
        objViewDir = normalize(objViewDir);
        SplatSHData sh = LoadSplatSH(idx);
        sh.col = color.rgb;
        col.rgb = ShadeSH(sh, objViewDir, _SHOrder, _SHOnly != 0);
    }
    else
    {
        col.rgb = color.rgb;
    }
    // col.a = min(color.a * opacityScale * h_convolution_scaling, 65000);
    col.a = min(color.a * opacityScale, 65000);
    
    // 采用原子加，来计算索引位置
    uint globalGemoLeftIndex;
    InterlockedAdd(_LeftNumArgs[0], 1, globalGemoLeftIndex);
    
    // 记录数据
    _GeomLeftData[globalGemoLeftIndex].conic_opacity = float4(conic_left_2d.x, conic_left_2d.y, conic_left_2d.z, col.a);
    _GeomLeftData[globalGemoLeftIndex].rgb_depth.x = f32tof16(col.r) << 16 | f32tof16(col.g);
    _GeomLeftData[globalGemoLeftIndex].rgb_depth.y = f32tof16(col.b) << 16 | f32tof16(centerLeftClipPos.w);
    _GeomLeftData[globalGemoLeftIndex].mean2D = mean_left_2d;
    
    #if defined(SINGLE_PASS)
    // 采用原子加，来计算索引位置
    uint globalGemoRightIndex;
    InterlockedAdd(_RightNumArgs[0], 1, globalGemoRightIndex);
    
    // 记录数据
    _GeomRightData[globalGemoRightIndex].conic_opacity = float4(conic_right_2d.x, conic_right_2d.y, conic_right_2d.z, col.a);
    _GeomRightData[globalGemoRightIndex].rgb_depth.x = f32tof16(col.r) << 16 | f32tof16(col.g);
    _GeomRightData[globalGemoRightIndex].rgb_depth.y = f32tof16(col.b) << 16 | f32tof16(centerRightClipPos.w);
    _GeomRightData[globalGemoRightIndex].mean2D = mean_right_2d;
    #endif
    
    // ---- AccuTile Code ---- //
    {
        bool isY = y_left_span < x_left_span;
        float disc = conic_left_2d.y * conic_left_2d.y - conic_left_2d.x * conic_left_2d.z;
        float t = 2.0f * log(col.a * ALPHA_T);
    
        // Set variables based on the isY flag
        float BLOCK_U = isY ? _TileConfig.y : _TileConfig.x;
        float BLOCK_V = isY ? _TileConfig.x : _TileConfig.y;
    
        if (isY)
        {
            rect_left_min = int2(rect_left_min.y, rect_left_min.x);
            rect_left_max = int2(rect_left_max.y, rect_left_max.x);
            
            bbox_left_min = float2(bbox_left_min.y, bbox_left_min.x);
            bbox_left_max = float2(bbox_left_max.y, bbox_left_max.x);
            
            bbox_left_argmin = float2(bbox_left_argmin.y, bbox_left_argmin.x);
            bbox_left_argmax = float2(bbox_left_argmax.y, bbox_left_argmax.x);
        }
    
        float2 intersect_min_line, intersect_max_line;
        float ellipse_min, ellipse_max;
        float min_line, max_line;
    
        // Initialize max line
        // Just need the min to be >= all points on the ellipse
        // and  max to be <= all points on the ellipse
        intersect_max_line = float2(bbox_left_max.y, bbox_left_min.y);
    
        min_line = rect_left_min.x * BLOCK_U;
        // Initialize min line intersections.
        if (bbox_left_min.x <= min_line)
        {
            // Boundary case
            intersect_min_line = ComputeEllipseIntersection(
                conic_left_2d, disc, t, mean_left_2d, isY, rect_left_min.x * BLOCK_U);
        }
        else
        {
            // Same as max line
            intersect_min_line = intersect_max_line;
        }
    
    
        // Loop over either y slices or x slices based on the `isY` flag.
        for (int u = rect_left_min.x; u < rect_left_max.x; ++u)
        {
            // Starting from the bottom or left, we will only need to compute
            // intersections at the next line.
            max_line = min_line + BLOCK_U;
            if (max_line <= bbox_left_max.x)
            {
                intersect_max_line = ComputeEllipseIntersection(
                    conic_left_2d, disc, t, mean_left_2d, isY, max_line);
            }
    
            // If the bbox min is in this slice, then it is the minimum
            // ellipse point in this slice. Otherwise, the minimum ellipse
            // point will be the minimum of the intersections of the min/max lines.
            if (min_line <= bbox_left_argmin.y && bbox_left_argmin.y < max_line)
            {
                ellipse_min = bbox_left_min.y;
            }
            else
            {
                ellipse_min = min(intersect_min_line.x, intersect_max_line.x);
            }
    
            // If the bbox max is in this slice, then it is the maximum
            // ellipse point in this slice. Otherwise, the maximum ellipse
            // point will be the maximum of the intersections of the min/max lines.
            if (min_line <= bbox_left_argmax.y && bbox_left_argmax.y < max_line)
            {
                ellipse_max = bbox_left_max.y;
            }
            else
            {
                ellipse_max = max(intersect_min_line.y, intersect_max_line.y);
            }
    
            // Convert ellipse_min/ellipse_max to tiles touched
            // First map back to tile coordinates, then subtract.
            int min_tile_v = max(rect_left_min.y,
                                 min(rect_left_max.y, (int)(ellipse_min / BLOCK_V))
            );
            int max_tile_v = min(rect_left_max.y,
                                 max(rect_left_min.y, (int)(ellipse_max / BLOCK_V + 1))
            );
    
            uint tiles_count = max_tile_v - min_tile_v;
            uint globalBinPointIndex;
            InterlockedAdd(_LeftNumArgs[1], tiles_count, globalBinPointIndex);
            // Loop over tiles and add to keys array
            for (int v = min_tile_v; v < max_tile_v; v++)
            {
                // For each tile that the Gaussian overlaps, emit a
                // key/value pair. The key is |  tile ID  |      depth      |,
                // and the value is the ID of the Gaussian. Sorting the values
                // with this key yields Gaussian IDs in a list, such that they
                // are first sorted by tile and then by depth.
                uint depth = FloatToUint(centerLeftClipPos.w);
                uint64_t tile_key = isY ? (u * (uint)_TileConfig.z + v) : (v * (uint)_TileConfig.z + u);
                tile_key <<= 32;
                _BinLeftPointListKey[globalBinPointIndex] = tile_key | ((uint64_t)depth & (((uint64_t)1U << 32) - 1));
                _BinLeftPointListValue[globalBinPointIndex] = globalGemoLeftIndex;
                globalBinPointIndex++;
            }
            // Max line of this tile slice will be min lin of next tile slice
            intersect_min_line = intersect_max_line;
            min_line = max_line;
        }
    }
    
    #if defined(SINGLE_PASS)
    // ---- AccuTile Code ---- //
    {
        bool isY = y_right_span < x_right_span;
        float disc = conic_right_2d.y * conic_right_2d.y - conic_right_2d.x * conic_right_2d.z;
        float t = 2.0f * log(col.a * ALPHA_T);
    
        // Set variables based on the isY flag
        float BLOCK_U = isY ? _TileConfig.y : _TileConfig.x;
        float BLOCK_V = isY ? _TileConfig.x : _TileConfig.y;
    
        if (isY)
        {
            rect_right_min = int2(rect_right_min.y, rect_right_min.x);
            rect_right_max = int2(rect_right_max.y, rect_right_max.x);
            
            bbox_right_min = float2(bbox_right_min.y, bbox_right_min.x);
            bbox_right_max = float2(bbox_right_max.y, bbox_right_max.x);
            
            bbox_right_argmin = float2(bbox_right_argmin.y, bbox_right_argmin.x);
            bbox_right_argmax = float2(bbox_right_argmax.y, bbox_right_argmax.x);
        }
    
        float2 intersect_min_line, intersect_max_line;
        float ellipse_min, ellipse_max;
        float min_line, max_line;
    
        // Initialize max line
        // Just need the min to be >= all points on the ellipse
        // and  max to be <= all points on the ellipse
        intersect_max_line = float2(bbox_right_max.y, bbox_right_min.y);
    
        min_line = rect_right_min.x * BLOCK_U;
        // Initialize min line intersections.
        if (bbox_right_min.x <= min_line)
        {
            // Boundary case
            intersect_min_line = ComputeEllipseIntersection(
                conic_right_2d, disc, t, mean_right_2d, isY, rect_right_min.x * BLOCK_U);
        }
        else
        {
            // Same as max line
            intersect_min_line = intersect_max_line;
        }
    
    
        // Loop over either y slices or x slices based on the `isY` flag.
        for (int u = rect_right_min.x; u < rect_right_max.x; ++u)
        {
            // Starting from the bottom or left, we will only need to compute
            // intersections at the next line.
            max_line = min_line + BLOCK_U;
            if (max_line <= bbox_right_max.x)
            {
                intersect_max_line = ComputeEllipseIntersection(
                    conic_right_2d, disc, t, mean_right_2d, isY, max_line);
            }
    
            // If the bbox min is in this slice, then it is the minimum
            // ellipse point in this slice. Otherwise, the minimum ellipse
            // point will be the minimum of the intersections of the min/max lines.
            if (min_line <= bbox_right_argmin.y && bbox_right_argmin.y < max_line)
            {
                ellipse_min = bbox_right_min.y;
            }
            else
            {
                ellipse_min = min(intersect_min_line.x, intersect_max_line.x);
            }
    
            // If the bbox max is in this slice, then it is the maximum
            // ellipse point in this slice. Otherwise, the maximum ellipse
            // point will be the maximum of the intersections of the min/max lines.
            if (min_line <= bbox_right_argmax.y && bbox_right_argmax.y < max_line)
            {
                ellipse_max = bbox_right_max.y;
            }
            else
            {
                ellipse_max = max(intersect_min_line.y, intersect_max_line.y);
            }
    
            // Convert ellipse_min/ellipse_max to tiles touched
            // First map back to tile coordinates, then subtract.
            int min_tile_v = max(rect_right_min.y,
                                 min(rect_right_max.y, (int)(ellipse_min / BLOCK_V))
            );
            int max_tile_v = min(rect_right_max.y,
                                 max(rect_right_min.y, (int)(ellipse_max / BLOCK_V + 1))
            );
    
            uint tiles_count = max_tile_v - min_tile_v;
            uint globalBinPointIndex;
            InterlockedAdd(_RightNumArgs[1], tiles_count, globalBinPointIndex);
            // Loop over tiles and add to keys array
            for (int v = min_tile_v; v < max_tile_v; v++)
            {
                // For each tile that the Gaussian overlaps, emit a
                // key/value pair. The key is |  tile ID  |      depth      |,
                // and the value is the ID of the Gaussian. Sorting the values
                // with this key yields Gaussian IDs in a list, such that they
                // are first sorted by tile and then by depth.
                uint depth = FloatToUint(centerLeftClipPos.w);
                uint64_t tile_key = isY ? (u * (uint)_TileConfig.z + v) : (v * (uint)_TileConfig.z + u);
                tile_key <<= 32;
                _BinRightPointListKey[globalBinPointIndex] = tile_key | ((uint64_t)depth & (((uint64_t)1U << 32) - 1));
                _BinRightPointListValue[globalBinPointIndex] = globalGemoRightIndex;
                globalBinPointIndex++;
            }
            // Max line of this tile slice will be min lin of next tile slice
            intersect_min_line = intersect_max_line;
            min_line = max_line;
        }
    }
    #endif
}

[numthreads(GROUP_SIZE, 1, 1)]
void CSIdentifyTileRanges (uint3 global_id : SV_DispatchThreadID)
{
    uint idx = SwizzleDispatchThreadId(global_id);
    if (idx >= _RO_NumArgs[1]) return;

    uint64_t currkey = _RO_BinPointListKey[idx];
    uint currtile = currkey >> 32;
    if (idx == 0)
    {
        _ImageRange[currtile].x = 0;
    }
    else
    {
        uint64_t prevkey = _RO_BinPointListKey[idx - 1];
        uint prevtile = prevkey >> 32;
        if (currtile != prevtile)
        {
            _ImageRange[prevtile].y = idx;
            _ImageRange[currtile].x = idx;
        }
    }

    if (idx == _RO_NumArgs[1] - 1)
    {
        _ImageRange[currtile].y = _RO_NumArgs[1];
    }
}

[numthreads(GROUP_SIZE, 1, 1)]
void CSInitImageRanges (uint3 global_id : SV_DispatchThreadID)
{
    uint idx = SwizzleDispatchThreadId(global_id);
    
    _ImageLeftRange[idx] = (uint2)0;

    #if defined(SINGLE_PASS)
    _ImageRightRange[idx] = (uint2)0;
    #endif
}


[numthreads(1, 1, 1)]
void CSInitNumArgs (uint3 global_id : SV_DispatchThreadID)
{
    _LeftNumArgs[0] = 0;
    _LeftNumArgs[1] = 0;
    _LeftNumArgs[2] = 1;
    _LeftNumArgs[3] = 1;
    _LeftNumArgs[4] = 1;
    _LeftNumArgs[5] = 1;
    _LeftNumArgs[6] = 1;
    _LeftNumArgs[7] = 1;

    #if defined(SINGLE_PASS)
    _RightNumArgs[0] = 0;
    _RightNumArgs[1] = 0;
    _RightNumArgs[2] = 1;
    _RightNumArgs[3] = 1;
    _RightNumArgs[4] = 1;
    _RightNumArgs[5] = 1;
    _RightNumArgs[6] = 1;
    _RightNumArgs[7] = 1;
    #endif
}

[numthreads(1, 1, 1)]
void CSInitSortArgs (uint3 global_id : SV_DispatchThreadID)
{
    {
        uint count = clamp(_LeftNumArgs[1], e_min, e_max);
    
        _LeftNumArgs[1] = count;
        _LeftNumArgs[2] = (count + PART_SIZE - 1) / PART_SIZE;
        _LeftNumArgs[3] = 1;
        _LeftNumArgs[4] = 1;
    
        int limitX = GROUP_SIZE * MAX_DISPATCH_GROUP;
        if (count > limitX)
        {
            _LeftNumArgs[5] = MAX_DISPATCH_GROUP;
            _LeftNumArgs[6] = count / limitX + 1;
        }
        else
        {
            _LeftNumArgs[5] = (count  + GROUP_SIZE - 1) / GROUP_SIZE;
            _LeftNumArgs[6] = 1;
        }

        _LeftNumArgs[7] = 1;
    }
    
    #if defined(SINGLE_PASS)
    {
        uint count = clamp(_RightNumArgs[1], e_min, e_max);
    
        _RightNumArgs[1] = count;
        _RightNumArgs[2] = (count + PART_SIZE - 1) / PART_SIZE;
        _RightNumArgs[3] = 1;
        _RightNumArgs[4] = 1;
    
        int limitX = GROUP_SIZE * MAX_DISPATCH_GROUP;
        if (count > limitX)
        {
            _RightNumArgs[5] = MAX_DISPATCH_GROUP;
            _RightNumArgs[6] = count / limitX + 1;
        }
        else
        {
            _RightNumArgs[5] = (count  + GROUP_SIZE - 1) / GROUP_SIZE;
            _RightNumArgs[6] = 1;
        }

        _RightNumArgs[7] = 1;
    }
    #endif
}

#if defined(SINGLE_PASS)
RWTexture2DArray<float4> _GSRenderTexture;
RWTexture2D<float2> _GSDepthTexture;
#else
RWTexture2D<float4> _GSRenderTexture;
RWTexture2D<float> _GSDepthTexture;
#endif

[numthreads(BLOCK_X, BLOCK_Y, 1)]
void CSRenderViewData (uint3 global_id : SV_DispatchThreadID, uint3 group_id : SV_GroupID)
{
    float W = _VecScreenParams.x * _VecScreenParams.z;
    float H = _VecScreenParams.y * _VecScreenParams.w;
    int w_offset = _VecScreenParams.x * (1.0 - _VecScreenParams.z) * 0.5;
    int h_offset = _VecScreenParams.y * (1.0 - _VecScreenParams.w) * 0.5;
    uint block_x = BLOCK_X * _TileScale;
    uint horizontal_blocks = (uint)((W + block_x - 1) / block_x);
    group_id.xy /= _TileScale;
    
    if (global_id.x < W && global_id.y < H)
    {
        // 计算迭代次数
        uint2 left_range = _RO_ImageLeftRange[group_id.y * horizontal_blocks + group_id.x];
        
        int left_toDo = left_range.y - left_range.x;
        
        if (left_toDo > 200 * BLOCK_SIZE) return;
        
        // 累计透明度、颜色和深度图输出
        float left_T = 1.0f;
        half3 left_color = 0.0f;
        float left_depth = 0.0f;
        float left_last_depth = 0.0f;

        // 遍历 Tile 中保存的高斯数据
        // 每个 thread 负责一个像素，逐像素累计高斯数据

        bool left_done = false;
        for (int j = 0; !left_done && j < left_toDo; j++)
        {
            int coll_id = _RO_BinLeftPointListValue[left_range.x + j];
            // 根据像素到 2D 高斯中心点的距离，计算衰减度
            float2 xy = _RO_GeomLeftData[coll_id].mean2D;
            
            float2 d = float2(xy.x - (float)global_id.x, xy.y - (float)global_id.y);

            float4 con_o = _RO_GeomLeftData[coll_id].conic_opacity;
            float power = -0.5f * (con_o.x * d.x * d.x + con_o.z * d.y * d.y) - con_o.y * d.x * d.y;
            // if (power > 0.0f)
            //     continue;

            // 计算 alpha 透明度
            float alpha = min(0.99f, con_o.w * exp(power));
            // if (alpha < 1.0f / 255.0f)
            //     continue;

            float test_T = left_T * (1 - alpha);
            if (test_T < TEST_ALPHA)
            {
                left_done = true;
                continue;
            }

            // 累加颜色
            half3 tmp_color;
            tmp_color.r = f16tof32(_RO_GeomLeftData[coll_id].rgb_depth.x >> 16);
            tmp_color.g = f16tof32(_RO_GeomLeftData[coll_id].rgb_depth.x);
            tmp_color.b = f16tof32(_RO_GeomLeftData[coll_id].rgb_depth.y >> 16);
            left_color += tmp_color * alpha * left_T;

            // 纪录截至时的最大深度
            left_last_depth = f16tof32(_RO_GeomLeftData[coll_id].rgb_depth.y);

            // 累加深度
            left_depth += left_last_depth * alpha * left_T;
            
            // 更新累积 alpha
            left_T = test_T;
        }

        #if defined(SINGLE_PASS)
        // 计算迭代次数
        uint2 right_range = _RO_ImageRightRange[group_id.y * horizontal_blocks + group_id.x];
        
        int right_toDo = right_range.y - right_range.x;
        
        if (right_toDo > 200 * BLOCK_SIZE) return;
        
        // 累计透明度、颜色和深度图输出
        float right_T = 1.0f;
        half3 right_color = 0.0f;
        float right_depth = 0.0f;
        float right_last_depth = 0.0f;

        // 遍历 Tile 中保存的高斯数据
        // 每个 thread 负责一个像素，逐像素累计高斯数据

        bool right_done = false;
        for (int j = 0; !right_done && j < right_toDo; j++)
        {
            int coll_id = _RO_BinRightPointListValue[right_range.x + j];
            // 根据像素到 2D 高斯中心点的距离，计算衰减度
            float2 xy = _RO_GeomRightData[coll_id].mean2D;
            
            float2 d = float2(xy.x - (float)global_id.x, xy.y - (float)global_id.y);

            float4 con_o = _RO_GeomRightData[coll_id].conic_opacity;
            float power = -0.5f * (con_o.x * d.x * d.x + con_o.z * d.y * d.y) - con_o.y * d.x * d.y;
            // if (power > 0.0f)
            //     continue;

            // 计算 alpha 透明度
            float alpha = min(0.99f, con_o.w * exp(power));
            // if (alpha < 1.0f / 255.0f)
            //     continue;

            float test_T = right_T * (1 - alpha);
            if (test_T < TEST_ALPHA)
            {
                right_done = true;
                continue;
            }

            // 累加颜色
            half3 tmp_color;
            tmp_color.r = f16tof32(_RO_GeomRightData[coll_id].rgb_depth.x >> 16);
            tmp_color.g = f16tof32(_RO_GeomRightData[coll_id].rgb_depth.x);
            tmp_color.b = f16tof32(_RO_GeomRightData[coll_id].rgb_depth.y >> 16);
            right_color += tmp_color * alpha * right_T;

            // 纪录截至时的最大深度
            right_last_depth = f16tof32(_RO_GeomRightData[coll_id].rgb_depth.y);

            // 累加深度
            right_depth += right_last_depth * alpha * right_T;
            
            // 更新累积 alpha
            right_T = test_T;
        }
        #endif
        
        #if defined(SINGLE_PASS)
        _GSRenderTexture[uint3(global_id.x + w_offset, H + h_offset - global_id.y, 0)] = float4(GammaToLinearSpace(left_color), 1.0 - left_T);
        _GSRenderTexture[uint3(global_id.x + w_offset, H + h_offset - global_id.y, 1)] = float4(GammaToLinearSpace(right_color), 1.0 - right_T);
        _GSDepthTexture[uint2(global_id.x + w_offset, H + h_offset - global_id.y)] = float2(left_last_depth, right_last_depth);
        #else
        _GSRenderTexture[uint2(global_id.x + w_offset, H + h_offset - global_id.y)] = float4(GammaToLinearSpace(left_color), 1.0 - left_T);
        _GSDepthTexture[uint2(global_id.x + w_offset, H + h_offset - global_id.y)] = left_last_depth;
        #endif
    }
}
